version: 2
jobs:
  build:
    docker:
    - image: angular/ngcontainer:latest
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Version Info
          command: |
            node --version \
              && yarn --version \
              && git --version

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # Build the libraries
      - run: yarn add --force node-sass
      - run: yarn build

      # Run unit tests!
      - run: yarn test

      # Store build artefacts on circle
      - store_artifacts:
          path: ~/repo/dist
          destination: dist