name: E2E Tests

on: [ push, fork ]

jobs:

  e2e-tests:
    name: DSP-APP E2E tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # gets additionally all tags which we need
      - uses: actions/setup-node@v6
        with:
          node-version: 22.12.0
          cache: 'npm'
      - name: Cache NX
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: nx-${{ github.workflow }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/nx.json') }}
          restore-keys: |
            nx-${{ github.workflow }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-
            nx-${{ github.workflow }}-${{ runner.os }}-
      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-
      - run: npm install
      - name: Install Cypress dependencies
        run: |
          cd ../dsp-das/apps/dsp-app/cypress
          npm install
      - name: Checkout DSP-API repo
        uses: actions/checkout@v6
        with:
          repository: dasch-swiss/dsp-api
          ref: main
          path: dsp-api
      - name: Start API
        run: |
          cd dsp-api
          make init-db-test
          docker compose -f docker-compose.yml up -d sipi ingest api
          ./webapi/scripts/wait-for-api.sh
      - name: Run e2e tests in CI
        if: github.event_name == 'push'
        run: |
          cd ../dsp-das
          npm run e2e-ci
      - name: Upload artifact
        uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: cypress-snapshots
          path: apps/dsp-app/cypress/fixtures/screenshots
      - name: Check Docker Container Logs
        run: |
          docker ps
          docker ps -q | xargs -I {} docker logs {}
