name: Unit Tests

on: [ push, fork ]

jobs:

  test:
    name: DSP-APP Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 22.12.0
          cache: 'npm'
      - name: Cache NX
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: nx-${{ github.workflow }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/nx.json') }}
          restore-keys: |
            nx-${{ github.workflow }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-
            nx-${{ github.workflow }}-${{ runner.os }}-
      - name: Install dependencies
        run: npm install
      - name: Run tests with coverage
        run: npm run unit-test-coverage-ci
        env:
          TZ: Europe/Zurich
          NX_PARALLEL: 10
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: unit-test-coverage
          fail_ci_if_error: false
